# Homebrew formula for Zornux (macOS + Linux).
#
# Generated by the release pipeline from packaging/homebrew/zornux.rb in the
# zornux/zornux repo on every version tag — do not edit by hand; edit the
# template instead. Install with:  brew install zornux/zornux/zornux
class Zornux < Formula
  desc "The English-readable programming language"
  homepage "https://zornux.dev"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-osx-arm64.tar.gz"
      sha256 "9363abf1c98817d44e39847ecd43592dc9a72c54b3724465126481e64cdae4c6"
    end
    on_intel do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-osx-x64.tar.gz"
      sha256 "5f26f80f520457e735631de4dc193113d6b91a61ed77df089a1050e0b453e9ed"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-linux-arm64.tar.gz"
      sha256 "0922d7a6848c230e251cb3fd3d07289ae8dca1821af552abeef5e8a64b5a8653"
    end
    on_intel do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-linux-x64.tar.gz"
      sha256 "0dbf9c46de05d63004905031397f3102a1f3d7ad1a707160fb054fb41767c2e2"
    end
  end

  def install
    bin.install "zornux"
  end

  test do
    assert_match "zornux", shell_output("#{bin}/zornux --version")
  end
end
