# Homebrew formula for Zornux (macOS + Linux).
#
# Generated by the release pipeline from packaging/homebrew/zornux.rb in the
# zornux/zornux repo on every version tag — do not edit by hand; edit the
# template instead. Install with:  brew install zornux/zornux/zornux
class Zornux < Formula
  desc "The English-readable programming language"
  homepage "https://zornux.dev"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-osx-arm64.tar.gz"
      sha256 "02b08884298ab7f7fc7f995ae31d5805f933cac38fe0ee2e521a56a97e1ffd7b"
    end
    on_intel do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-osx-x64.tar.gz"
      sha256 "004b0f1c2fc243329ec93587f80037f7b12c59a3e871adac2b8ca28b7b7ee92c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-linux-arm64.tar.gz"
      sha256 "20136c23725c9e6e8d54bb668ff1988bf24b5687b3497ccae996d51df01c0547"
    end
    on_intel do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-linux-x64.tar.gz"
      sha256 "5abb492c823ff6c3933e219b8e6520ed3541902c426aa025218ff2bf0d766752"
    end
  end

  def install
    bin.install "zornux"
  end

  test do
    assert_match "zornux", shell_output("#{bin}/zornux --version")
  end
end
