# Homebrew formula for Zornux (macOS + Linux).
#
# Generated by the release pipeline from packaging/homebrew/zornux.rb in the
# zornux/zornux repo on every version tag — do not edit by hand; edit the
# template instead. Install with:  brew install zornux/zornux/zornux
class Zornux < Formula
  desc "The English-readable programming language"
  homepage "https://zornux.dev"
  version "1.5.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-osx-arm64.tar.gz"
      sha256 "bbfe902edde9981c6fac3893192720a9e9224edea798b541ce232a7db58211ce"
    end
    on_intel do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-osx-x64.tar.gz"
      sha256 "c75ec0d51bc09e1d0c80f68b112b8c7122031e468699a5fad5dae0a59eaf617d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-linux-arm64.tar.gz"
      sha256 "20779c0887bb2aeec364bc8316e9cfa6c8e7de71d80461de5b6df42475b0bb74"
    end
    on_intel do
      url "https://github.com/zornux/zornux-dist/releases/download/v#{version}/zornux-#{version}-linux-x64.tar.gz"
      sha256 "ea3e08c1506a5d44f34fa94311aa05b4193e8da445f35d09a0248c36670e4235"
    end
  end

  def install
    bin.install "zornux"
  end

  test do
    assert_match "zornux", shell_output("#{bin}/zornux --version")
  end
end
